# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

In [2]:
import numpy as np

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [43]:
data = np.loadtxt('minutes_n_ingredients.csv', dtype=np.int32, delimiter = ',', skiprows = 1)
res = data[:5]
print(res)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [8]:
print("Минимальное значение:","\n", np.min(res, axis=1))
print("Максимум:","\n", np.max(res, axis=1))
print('Среднее значение:','\n', np.mean(res, axis = 1))
print('Медиана:','\n', np.median(res, axis = 1))

Минимальное значение: 
 [16  7  6  5 14]
Максимум: 
 [127244  23891  94746  67660 157911]
Среднее значение: 
 [42440.          7974.33333333 31587.33333333 22557.
 52661.66666667]
Медиана: 
 [60. 25. 10.  6. 60.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [10]:
res = data[:,1]
print(np.quantile(res, 0.75, axis = 0))
q_075 = np.quantile(data[:, 1], 0.75)
data[:, 1] = np.clip(data[:, 1], a_min=0, a_max=q_075)
data[:10]

65.0


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14],
       [152828,     40,      7],
       [ 33941,     18,      9],
       [446597,     15,      5],
       [366174,      7,      9],
       [ 74205,     20,      7]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [19]:
res = data[:, 1:2]
print(np.sum(res==0))
np.place(res, res < 1, 1)
print(res)

0
[[60]
 [25]
 [10]
 ...
 [65]
 [ 5]
 [65]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [20]:
print(len(np.unique(data[:, :1])))

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [23]:
unique, counts = np.unique(data[:,2], return_counts=True)
print(f'уникальных значений {len(unique)}')
dict(zip(counts, unique))

уникальных значений 37


{13: 1,
 926: 2,
 2895: 3,
 5515: 4,
 7913: 5,
 9376: 6,
 10628: 7,
 10951: 8,
 10585: 9,
 9591: 10,
 8297: 11,
 6605: 12,
 4997: 13,
 3663: 14,
 2595: 15,
 1767: 16,
 1246: 17,
 790: 18,
 573: 19,
 376: 20,
 217: 21,
 161: 22,
 105: 23,
 69: 24,
 50: 25,
 28: 26,
 16: 28,
 12: 30,
 3: 35,
 1: 39,
 2: 33}

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [28]:
data[data[:, 2] <= 5]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [47]:
print(np.max(data[:, 2] // data[:, 1]))

23


C:\Users\islam\AppData\Local\Temp\ipykernel_8976\888115417.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.max(data[:, 2] // data[:, 1]))


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [34]:
print(np.mean(data[np.argsort(data[:,1])][-100:, 2]))

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [37]:
n = 10 
index = np.random.choice(data.shape[0], n, replace=False)  
print(data[index])

[[ 13215     35      8]
 [184490     10      8]
 [411474     45     13]
 [305368     65      6]
 [205794     30      7]
 [145940      5     10]
 [239604      5      7]
 [133160     25      5]
 [397294    120     14]
 [ 78660    368     17]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
print(data[data[:,2]<np.mean(data[:,2])].shape[0]/data.shape[0]*100)

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [38]:
ndata = np.c_[data, (data[:, 1] < 20) & (data[:,2] < 5)]
ndata

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [51]:
data[(data[:, 1] < 20) & (data[:,2] < 5)].size / data.size * 100

5.093

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [ ]:
arr1 = data[data[:,1] < 10]
arr2 = data[(data[:,1] >= 10) & (data[:,1] < 20)]
arr3 = data[20 <= data[:,1]]
df = np.min([arr1.shape[0], arr2.shape[0], arr3.shape[0]])
res = np.array([arr1[:df], arr2[:df], arr3[:df]])
print(res.shape)
print(res)